### ISSUE TITLE
style is hard coded and icon to delete is half under the preview one to delete.

### ISSUE THREAD

**Issue by jerome-diver** [Abd-Alwahab/image-upload-react#1]
style is hard coded and icon to delete is half under the preview one to delete.
How to just indicate the correct z-index to the preview layer and to the icon to delete action ?

**Comment by prionkor** [comment]
Very useful code, Dependency can be removed by passing the icon as props.

**Comment by Abd-Alwahab** [comment]
hey @jerome-diver 
Thank you so much for notify me, I updated the package with more custom props , 

new props:

00-defaultDeleteIconSize: change the default delete icon size.
01-defaultDeleteIconColor: change the default delete icon color.
02-deleteIcon: custom delete icon that you can set.


problems solved 

00-the z-index problem on the delete icon 

sandbox example: 
https://codesandbox.io/s/react-upload-image-7im7r

please let me know if anything went wrong. 

Thank you so much 
AbdAlwahab

**Comment by jerome-diver** [comment]
thank you very much for your job.
I would see a unique "deleteIconStyle" prop instead of 2 props "deleteIconSize" and "deleteIconColor" ("deleteIcon" is very good).
Do you want that i take time to try to do it ?

**Comment by Abd-Alwahab** [comment]
Hey @jerome-diver 
I am using a react-icons to render the default delete icon , the react-icons component that I am using dose not accept a style object attribute so I added the custom delete icon prop, is there any idea that you have around this ?

**Comment by jerome-diver** [comment]
@Abd-Alwahab this is a personal choice, i'm not sure there can have some objective reasons to choose this more than an other one icons react tool.
For example, i'm using "fortawesome" for my icons.

But what i'm thinking to be more objective to let user choose his own and not overload libraries dependencies.
I mean... use a button to delete and let choice for an icon (so then you no more need dependency, and the user will use his own).
So then the use of react-icons should be just show inside the example code to provide the way to pass an icon instead of using the default (and zero dependency) button to delete (and so, the same for icon to upload).

But, it is a way to look at things to minimize dependencies required. The idea is to reduce your library weight, and then, for users, there own libraries total load time too...

 As long as it is your code, you will choose to do as you prefer.

By the way, you've changed also the index.css (better) and now, it is ok, the icon is up to the image preview.

To style any other icons, instead of passing a style to the object, it can be a parent div to surround a style. I think that this is more about a CSS problem to do things the way it can most probably be compatible with the most other icons tools (including react-icons). So then, your icon, what ever it is, will be filled inside this parent, so the parent will be styled when a "iconStyle" prop will be given.

An other one things that can also improve the interest of your library and that is "on edge of the actuality", is to care about React.js in SSR mode (Server side rendering), and the use to be compatible with a form to provide for "multer.js" (an Express.js upload file or any images ) on server side. So then to be able to get an "input" HTML tag with the enctype required.
Also, to be able to be compatible with any device to be more responsive as mobile device doesn't use drag and drop things, it is nice to be able to get a real input with a button (or icon) instead. (On my code, i add an input that have interaction with your library to be updated when a new image is there... At submit time, the file will go to server side (not before... just a preview in client side).
(Maybe you would prefer that i move this idea in a new "issue" as an improvement idea ?)
